---
- name: Get Helm version
  ansible.builtin.command: /usr/local/bin/helm version
  ignore_errors: true
  changed_when: false
  register: helm

- name: Set helm_present fact
  ansible.builtin.set_fact:
    helm_present: >
      {{ not helm.failed and helm.stdout
      | regex_search(helm_version
      | regex_escape()) }}

- name: Include Helm installation
  ansible.builtin.include_tasks: setup.yaml
  when: not helm_present

- name: Git is present for Helm plugin installation
  become: true
  ansible.builtin.apk:
    name: git
    state: present

# Improves the idempotency check in kubernetes.core.helm.
- name: Helm Diff plugin is present
  become: true
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    plugin_version: '{{ helm_diff_plugin_version }}'

- name: Kubernetes.core.k8s module requirement is present
  become: true
  ansible.builtin.pip:
    name: kubernetes=={{ helm_kubernetes_python_version }}
