---
- name: Install GNU tar on Alpine
  ansible.builtin.apk:
    name: tar
    state: present
  when: ansible_distribution == 'Alpine'
  become: true

- name: Temporary download folder is present
  ansible.builtin.file:
    path: /tmp/helm
    state: directory

- name: Download Helm binary
  ansible.builtin.unarchive:
    src: https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz
    remote_src: yes
    dest: /tmp/helm
    include:
      - linux-amd64/helm

- name: Install Helm binary
  ansible.builtin.copy:
    remote_src: yes
    src: /tmp/helm/linux-amd64/helm
    dest: /usr/local/bin
    mode: "755"
  become: true

- name: Remove extracted Helm folder
  ansible.builtin.file:
    path: /tmp/helm
    state: absent

- name: Set helm_present fact to yes
  ansible.builtin.set_fact:
    helm_present: yes
