---
stages:
  - test

default:
  image: python:3.11.7-slim-bookworm
  cache:
    paths:
      - .cache/pip

.ansible:
  before_script:
    - apt-get update
    - apt-get install --yes git
    - pip install -r requirements.txt
    - ansible-galaxy install -r requirements.yml

.terraform:
  before_script:
    - apt-get update
    - apt-get install --yes wget unzip
    - wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
    - unzip /tmp/terraform.zip
    - mv terraform /usr/local/bin

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  TF_VERSION: 1.6.5
  ANSIBLE_HOST_KEY_CHECKING: "0"

lint:
  stage: test
  before_script:
    - !reference [.ansible, before_script]
  script:
    - ansible-lint --rules-dir rules
    - ansible-argspec-lint roles

test:
  stage: test
  parallel:
    matrix:
      - ROLE:
          - k3s
          - observability
          - argo
          - cert_manager
  before_script:
    - !reference [.ansible, before_script]
    - !reference [.terraform, before_script]
  script:
    - cd roles/$ROLE
    - molecule test
