---
stages:
  - test

default:
  before_script:
    - pip install -r requirements.txt
    - ansible-galaxy install -r requirements.yml

lint:
  stage: test
  image: python:3.10.6-slim-bullseye
  script:
    - ansible-lint -P production
    - ansible-argspec-lint roles

test-k3s:
  stage: test
  image: docker.houseofkummer.com/homelab/dockops:0.6.0
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "0"
  script:
    - cd roles/k3s
    - molecule test

test-observability:
  stage: test
  image: docker.houseofkummer.com/homelab/dockops:0.6.0
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "0"
  script:
    - cd roles/observability
    - molecule test
  # Job dependencies are used to limit execution to one job at a time to conserve
  # resources, as each job creates a VM.
  needs:
    - test-k3s

test-argo:
  stage: test
  image: docker.houseofkummer.com/homelab/dockops:0.6.0
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "0"
  script:
    - cd roles/argo
    - molecule test
  needs:
    - test-observability

test-cert-manager:
  stage: test
  image: docker.houseofkummer.com/homelab/dockops:0.6.0
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "0"
  script:
    - cd roles/cert_manager
    - molecule test
  needs:
    - test-argo
