---
stages:
  - test

lint:
  stage: test
  image: python:3.10.6-slim-bullseye
  script:
    - pip install poetry
    - poetry install
    - poetry run ansible-galaxy install -r requirements.yml
    - poetry run ansible-lint -P production
    - poetry run yamllint .

test-k3s:
  stage: test
  image: docker.houseofkummer.com/homelab/dockops:0.6.0
  variables:
    ANSIBLE_HOST_KEY_CHECKING: '0'
  script:
    - pip install poetry
    - poetry install
    - poetry run ansible-galaxy install -r requirements.yml
    - cd roles/k3s
    - poetry run molecule test

test-observability:
  stage: test
  image: docker.houseofkummer.com/homelab/dockops:0.6.0
  variables:
    ANSIBLE_HOST_KEY_CHECKING: '0'
  script:
    - pip install poetry
    - poetry install
    - poetry run ansible-galaxy install -r requirements.yml
    - cd roles/observability
    - poetry run molecule test
  # Job dependencies are used to limit execution to one job at a time to conserve
  # resources, as each job creates a VM.
  needs:
    - test-k3s

test-argo:
  stage: test
  image: docker.houseofkummer.com/homelab/dockops:0.6.0
  variables:
    ANSIBLE_HOST_KEY_CHECKING: '0'
  script:
    - pip install poetry
    - poetry install
    - poetry run ansible-galaxy install -r requirements.yml
    - cd roles/argo
    - poetry run molecule test
  needs:
    - test-observability

test-cert-manager:
  stage: test
  image: docker.houseofkummer.com/homelab/dockops:0.6.0
  variables:
    ANSIBLE_HOST_KEY_CHECKING: '0'
  script:
    - pip install poetry
    - poetry install
    - poetry run ansible-galaxy install -r requirements.yml
    - cd roles/cert_manager
    - poetry run molecule test
  needs:
    - test-argo
