---
namespace: lkummer
name: homelab
version: 0.1.1
readme: README.md
authors:
  - Lior Kummer <lior@sneakybugs.com>

# Optional
# description: your collection description

license:
  - GPL-3.0-or-later

tags: []
dependencies: {}

repository: https://github.com/LKummer/ansible-collection-homelab
homepage: https://github.com/LKummer/ansible-collection-homelab
documentation: https://github.com/LKummer/ansible-collection-homelab
issues: https://github.com/LKummer/ansible-collection-homelab/issues

build_ignore:
  - poetry.lock
  - pyproject.toml
