---
collections:
  - name: kubernetes.core
    version: 3.0.0
  - name: community.general
    version: 8.0.2
  - name: community.crypto
    version: 2.16.0
  - name: cloud.terraform
    version: 2.0.0
