---
collections:
  - name: kubernetes.core
    version: 2.3.2
  - name: community.general
    version: 6.1.0
  - name: community.crypto
    version: 2.9.0
  - name: cloud.terraform
    version: 1.1.0
