---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify all Kubernetes pods are running or succeeded
      become: true
      kubernetes.core.k8s_info:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        kind: Pod
      register: pod_list
      until: pod_list.resources | map(attribute="status.phase") is subset(["Running", "Succeeded"])
      retries: 6
      delay: 10

    - name: Get pods in target namespace of Redis ArgoCD Application
      become: true
      kubernetes.core.k8s_info:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        kind: Pod
        namespace: test
      register: test_pod_list
      until: 0 < (test_pod_list.resources | length)
      retries: 3
      delay: 10
