---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify all Kubernetes pods are running or succeeded
      become: true
      kubernetes.core.k8s_info:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        kind: Pod
      register: pod_list
      until: pod_list.resources | map(attribute="status.phase") is subset(["Running", "Succeeded"])
      retries: 6
      delay: 10

    - name: Verify Cert Manager created self signed CA secret
      become: true
      kubernetes.core.k8s_info:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        kind: Secret
        namespace: cert-manager
        name: test-ca
      register: test_ca
      until: 1 == (test_ca.resources | length)
      retries: 3
      delay: 10
