---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get all Kubernetes pods
      become: true
      kubernetes.core.k8s_info:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        kind: Pod
      register: pod_list

    - name: All pods are running or completed
      ansible.builtin.assert:
        that: item.status.phase == "Running" or item.status.phase == "Succeeded"
        quiet: true
      with_items: '{{ pod_list.resources }}'

    - name: Get secret containing self signed CA
      become: true
      kubernetes.core.k8s_info:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        kind: Secret
        namespace: cert-manager
        name: test-ca
      register: test_ca

    - name: Cert Manager created self signed CA secret
      ansible.builtin.assert:
        that: 1 == (test_ca.resources | length)
