---
- name: Check K3s version
  ansible.builtin.command: /usr/local/bin/k3s --version
  ignore_errors: true
  changed_when: false
  register: k3s
  become: true

- name: Include K3s setup
  ansible.builtin.include_tasks: setup.yaml
  when: k3s.failed or not k3s.stdout | regex_search(k3s_version | regex_escape())

- name: Slurp K3s configuration
  ansible.builtin.slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: k3s_config_base64
  become: true

- name: Decode K3s config
  ansible.builtin.set_fact:
    k3s_config: '{{ k3s_config_base64.content | b64decode }}'

- name: Replace Kubeconfig server address
  ansible.builtin.set_fact:
    k3s_config: '{{ k3s_config | replace("127.0.0.1", ansible_default_ipv4.address) }}'

- name: Kubeconfig folder is present
  ansible.builtin.file:
    name: ./secrets
    state: directory
    mode: '600'
  delegate_to: localhost
  become: false

- name: Write Kubeconfig
  ansible.builtin.copy:
    dest: ./secrets/k3s.{{ ansible_default_ipv4.address }}.yaml
    content: '{{ k3s_config }}'
    mode: '600'
  delegate_to: localhost
  become: false
