---
- name: Set update-extlinux.conf
  ansible.builtin.replace:
    path: /etc/update-extlinux.conf
    after: default_kernel_opts=
    regexp: '"(?:cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory )?([\s\w=]*)"'
    replace: '"cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory \1"'
  register: extlinux
  become: true

- name: Run update-extlinux
  ansible.builtin.command: update-extlinux
  when: extlinux.changed
  become: true

- name: Reboot after update-extlinux
  ansible.builtin.reboot: {}
  when: extlinux.changed
  become: true

- name: Install curl
  ansible.builtin.apk:
    name: curl
    state: present
  become: true

- name: Get K3s installation script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/get-k3s
    mode: '644'

- name: Install K3s
  ansible.builtin.command: sh /tmp/get-k3s
  environment:
    INSTALL_K3S_VERSION: '{{ k3s_version }}'
  become: true
  changed_when: true

- name: Reboot after K3s installation
  ansible.builtin.reboot: {}
  become: true

- name: Wait before grabbing config
  ansible.builtin.wait_for:
    timeout: 10
