---
- name: Set update-extlinux.conf
  become: true
  ansible.builtin.replace:
    path: /etc/update-extlinux.conf
    after: default_kernel_opts=
    regexp: '"(?:cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory )?([\s\w=]*)"'
    replace: '"cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory \1"'

- name: Run update-extlinux
  become: true
  ansible.builtin.command: update-extlinux
  when: not ansible_check_mode
  # Avoid showing changes, as the command is idempotent and dependent on the above task.
  changed_when: false

- name: Install curl
  become: true
  ansible.builtin.apk:
    name: curl
    state: present

- name: Get K3s installation script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/get-k3s
    mode: '644'

- name: Install K3s
  become: true
  ansible.builtin.command: sh /tmp/get-k3s
  environment:
    INSTALL_K3S_VERSION: '{{ k3s_version }}'
  changed_when: true

- name: Reboot after K3s installation
  become: true
  ansible.builtin.reboot: {}

- name: Wait before grabbing config
  ansible.builtin.wait_for:
    timeout: 10
