---
- name: Converge
  hosts: all
  tasks:
    - name: Include homelab.k3s
      ansible.builtin.include_role:
        name: k3s

    - name: Include homelab.cert_manager
      ansible.builtin.include_role:
        name: cert_manager
      vars:
        cert_manager_clusterissuer_enabled: false
        cert_manager_cloudflare_email: unused@exmaple.com
        cert_manager_cloudflare_token: UNUSED
        cert_manager_cloudflare_zone: UNUSED

    - name: Include homelab.observability
      ansible.builtin.include_role:
        name: observability
      vars:
        observability_grafana_host: grafana.example.com
        observability_grafana_user: admin
        observability_grafana_password: admin
