---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: '{{ molecule_no_log }}'
  tasks:
    - name: Ensure test secrets directory exists
      ansible.builtin.file:
        path: /tmp/homelab-collection-test/secrets
        state: directory
        mode: '0700'

    - name: Generate SSH key pair
      community.crypto.openssh_keypair:
        path: /tmp/homelab-collection-test/secrets/id_k3s_test
        type: ed25519
      register: ssh_keypair

    - name: Create machine
      cloud.terraform.terraform:
        project_path: terraform/
        force_init: true
        variables:
          cloud_init_public_keys: '{{ ssh_keypair.public_key }}'
      register: tf_create

    - name: Populate instance config
      ansible.builtin.set_fact:
        instance_conf:
          - instance: instance
            address: '{{ tf_create.outputs.ssh_ip.value }}'
            user: '{{ tf_create.outputs.user.value }}'
            port: '{{ tf_create.outputs.ssh_port.value | string }}'
            identity_file: '{{ ssh_keypair.filename }}'

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_yaml }}
        dest: '{{ molecule_instance_config }}'
        mode: '0600'
