---
argument_specs:
  main:
    short_description: >
      Configures a centralized observability stack for collecting logs, metrics and traces.
    options:
      observability_kube_prometheus_stack_chart_version:
        type: str
        default: 54.2.2
        description: >
          Version of prometheus-community/kube-prometheus-stack Helm chart
          deployed.
      observability_loki_chart_version:
        type: str
        default: 5.38.0
        description: Version of grafana/loki Helm chart deployed.
      observability_tempo_chart_version:
        type: str
        default: 1.7.1
        description: Version of grafana/tempo Helm chart deployed.
      observability_opentelemetry_operator_chart_version:
        type: str
        default: 0.43.0
        description: Version of OpenTelemetry Operator Helm chart deployed.
      observability_fluent_operator_chart_version:
        type: str
        default: 2.6.0
        description: Version of Fluent Operator Helm chart deployed.
      observability_grafana_host:
        type: str
        required: true
        description: Hostname of the Grafana instance.
      observability_grafana_user:
        type: str
        required: true
        description: Username of the default Grafana administrator.
      observability_grafana_password:
        type: str
        required: true
        description: Password of the default Grafana administrator.
      observability_service_monitor_selector:
        type: dict
        default: {}
        description: Default service monitor selector for Prometheus.
      observability_pod_monitor_selector:
        type: dict
        default: {}
        description: Default pod monitor selector for Prometheus.
