---
# For latest stable release, see https://update.k3s.io/v1-release/channels
#!! echo k3s_version: $(wget -qO- https://update.k3s.io/v1-release/channels | jq -r '.data[] | select(.id == "stable") | .latest')
k3s_version: v1.27.3+k3s1
