---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: '{{ molecule_no_log }}'
  tasks:
    # Developer must implement.
    - name: Destroy VM
      ansible.builtin.command:
        chdir: terraform
        cmd: terraform destroy -auto-approve
      changed_when: true

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config
      ansible.builtin.set_fact:
        instance_conf: {}

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: '{{ molecule_instance_config }}'
        mode: '0600'
